seed : 2791

locale : en_US

data :
  dir : data
  raw :
    dir   : raw
    url   : https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip
    local : Coursera-SwiftKey.zip
  clean :
    dir : clean

subsampling:
  perc : 1


